version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-20
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - circle-cache
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run Tests
          command: stack --no-terminal test
      - run:
          name: Install Executable
          command: stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: circle-cache
          paths:
            - "~/.stack"
            - ".stack-work"
      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: ~/.local/bin/toon-exe
          destination: toon-exe
      - run:
          name: Store Build Number
          command: mkdir -p workspace && echo $CIRCLE_BUILD_NUM > workspace/build_num
      - persist_to_workspace:
          root: workspace
          paths:
            - build_num

  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./scripts/deploy.py $(cat workspace/build_num)"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
